[book]
title = "Projects"
authors = ["YukunHan1999"]
language = "zh"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/YukunHan1999/para"
default-theme = "light"
preferred-dark-theme = "ayu"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.playground]
editable = true
line-numbers = true
